services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shinomoto926!
      MYSQL_DATABASE: curriculum-portal
      # 開発環境での設定
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # 開発環境ではinit.sqlの実行を制御
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pshinomoto926!",
        ]
      timeout: 20s
      retries: 10
      interval: 10s

  # Node.js Application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=shinomoto926!
      - DB_NAME=curriculum-portal
      - DB_PORT=3306
      - NODE_ENV=development
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=5717beb0435d9de18748f91fc0be629371b2ef694d79689fb60b0764724981fc1db009971e523783bbb6313bb9f45e39f2393dbfc845abeac55df03cef39ae52
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/",
        ]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
